neo4j:
  host: test_neo4j-ansible-inventory_neo4j
  bolt_port: 7687
  # user: neo4j
  # password: neo4j
ansible:
  inventory_path: test_ansible_dir/inventory
  playbook_dir: test_ansible_dir
  use_vault: false
  # password: vault-password
label_name:
  group_label: ANSIBLE_GROUP
  host_label: ANSIBLE_HOST
  vars_label: ANSIBLE_VARS
  inclusion_relation_type: HAS
